### ISSUE TITLE
master 브랜치에 머지될 시 Heroku에 자동으로 배포되도록 해야 합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/not-a-bean#12]
# 설명
https://devcenter.heroku.com/articles/github-integration

Heroku는 GitHub integration을 지원합니다. `master` 브랜치에 머지될 때마다 자동으로 배포가 이루어지도록 할 수 있습니다.

**Comment by limgit** [comment]
다음과 같은 단계를 따라 Heroku에 이 레포를 연결했습니다.

1. Heroku - App - Deploy 설정
2. Deployment method에서 GitHub 선택하고 계정 연동
3. 레포 찾아서 연결
4. Automatic deploys에서 Wait for CI to pass before deploy 체크하고 Enable

다만 여기에서 Travis CI와의 연동이 필요한지 여부를 모르겠습니다. 그냥 Heroku에서 master에 푸시되는 대로 바로 deploy하도록 설정을 켜놓는 것으로 끝나는 것 같거든요.
한편으론 Travis 연동이 필요할지도 모른다는 생각이 드는게, Wait for CI to pass before deploy 설정 때문입니다. Heroku CI가 아닌 외부 CI를 쓰는 경우엔 해당 CI에서 Heroku쪽에 CI pass 여부를 알려줄 방법이 필요할 것 같은데 이게 Travis와 연동하는 과정인가 싶기도 합니다.
사실 그냥 PR 단계에서 CI pass를 모두 체크하고 들어가는거라 애초에 Wait for CI to pass before deploy 설정이 필요한지도 의문이긴 하지만... 

그래서 우선 현상태로 놔두고 이 이슈는 열어둔 채, 후에 다른 PR을 머지하다가 뭔가 작동이 이상하면 Travis 연동 작업을 진행하고, 그렇지 않으면 그때 이 이슈를 닫을까 하는데 괜찮을까요? @JeongHoJeong

**Comment by JeongHoJeong** [comment]
넵 좋을 것 같습니다! @limgit

**Comment by limgit** [comment]
방금 #23 PR이 머지되면서 master automatic deploy가 정상 작동하는지 확인했는데, Heroku에서 "Deployed 104685a8" 메시지가 뜬 것을 확인했습니다. 현재 상태에서 문제가 없는 것 같으니 이 이슈는 일단 닫도록 하겠습니다. @JeongHoJeong
