### ISSUE TITLE
PR 템플릿에 수정이 필요합니다.

### ISSUE THREAD

**Issue by limgit** [binarysound/not-a-bean#20]
# 설명
현재 PR 템플릿은 아래와 같습니다:

> # 관련 이슈
>
> # 설명

현재 상태도 나쁘지 않으나, 보통 PR이 특정 이슈를 해결하고 해당하는 이슈가 바로 닫힌다는 점을 고려할 때, 아래의 형태로 바꾸는 것이 좋을것 같습니다.

> # 관련 이슈
> Close
>
> # 설명

PR 템플릿은 작성해줘야 하는 부분에 대한 일종의 Reminder 처럼 사용되기 때문에 이를 이용해 Close 키워드를 넣는 것을 잊지 않도록 해줄 수 있을 것 같습니다. 만일 특정 이슈를 닫고자 하지 않는다면 그냥 Close 키워드를 지우고 PR을 작성하면 됩니다.

해당 내용이 괜찮다고 생각하시면 작업하겠습니다. 다른 대안이 있거나 필요없다고 생각하시면 의견 주세요.

**Comment by JeongHoJeong** [comment]
풀 리퀘스트 내용에 `Close #n`의 형태의 내용이 존재하면, 해당 풀 리퀘스트가 머지될 시 `#n`번 이슈가 자동으로 닫히게 되나요? 아니면 그냥 리마인더 차원에서의 텍스트인건가요?

**Comment by limgit** [comment]
자동으로 닫히게 됩니다. 그부분 설명을 빼먹었네요 :). 이 [링크](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/) 참조해주세요

**Comment by JeongHoJeong** [comment]
오 좋군요. 그런데 다만 close보다는 resolve는 어떨까요? close는 닫기만 한다는 느낌이라서요. 제목인 `관련 이슈`와는 살짝 어울리지 않는 것 같은 느낌이 좀 드네요. 아래와 같은 대안은 어떻게 생각하시나요?

> # 해결하는 이슈
> Resolve

**Comment by limgit** [comment]
아 "관련 이슈"라는 이름을 여전히 남겨둔 이유는 PR이 직접적으로 닫지는 않으나 관련된 이슈가 있는 경우도 발생할 수 있기 때문입니다. 다시 말해서

> # 관련 이슈
> Close (or Resolve, Fix) #sth1, Close #sth2 
> #sth3 , #sth4 

같은 형태도 발생할 수 있다고 보았고, 이 경우엔 "관련 이슈가 sth1, sth2, sth3, sth4가 있는데 이 중 sth1과 sth2를 닫는다" 라고 해석하는 편이 자연스러운 것 같았습니다.

Close, Resolve, Fix 중 어느것을 쓰든 저는 괜찮은데, 개인적으로 Fix는 뭔가 bug fix에만 한정되는 느낌이 있어서 좀 기피되네요. 사실 단어를 뭐로 쓰느냐보다 Close로 쓸 지 Closes로 쓸 지를 더 고민중이었어서 😭

**Comment by JeongHoJeong** [comment]
아하 그렇군요. 그럼 closes 외의 예시(resolves, fixes, relates...)들도 가볍게 써 두는 정도면 좋을 것 같은데 어떠세요?
전 `close`와 `closes` 둘 다 같은 기능을 한다면 전 어느 쪽도 상관 없습니다. 다만 `closes` 쪽이 좀 더 타동사의 의미가 강한 것 같아서 (뒤에 목적어를 써야만 할 것 같은 인상이라) 마음에 들긴 하네요. @limgit

**Comment by limgit** [comment]
음 그럼

> # 관련 이슈
> [닫고자 하는 이슈의 경우, Closes, Resolved, Fixes 등의 문구와 함께 기술합니다]
>
> # 설명

의 형태가 되려나요? 개인적으론 처음에 이런 기술형의 템플릿을 생각했다가 약간 난잡해보여서 맨 처음 방식처럼 제안한거긴 합니다. 근데 이쪽도 괜찮을거 같네요.
