### ISSUE TITLE
브랜치 보호 기능 활성화

### ISSUE THREAD

**Issue by limgit** [binarysound/not-a-bean#4]
# 개요
master branch를 보호해 개발 과정에서 일어날 수 있는 실수를 미연에 방지합니다.

# 본문
Settings - Branches - Branch Protection Rules 에 규칙을 추가하는 것으로 브랜치를 보호할 수 있습니다.
최근에 이 설정 페이지에도 약간의 변동이 생겼나 보네요.
Require pull request reviews before merging, Include administrators 정도를 활성화해주면 될 것 같습니다.
나머지는... 아직 저장소 규모가 작으니 굳이 필요 없을 것 같아요.

마스터 브랜치 보호 기능을 활성화 해도 괜찮다고 생각하실때 이 이슈에 코멘트 주세요. 활성화 하도록 하겠습니다.

**Comment by JeongHoJeong** [comment]
넵, 동의합니다.

**Comment by limgit** [comment]
![image](https://user-images.githubusercontent.com/10260432/45201129-f2102c80-b2ae-11e8-9439-ddf7fc4cd42f.png)

마스터에 해당 형식으로 보호 규칙 생성했습니다.
