### ISSUE TITLE
프론트 SPA 최초 셋업이 필요합니다.

### ISSUE THREAD

**Issue by JeongHoJeong** [binarysound/not-a-bean#6]
# 필요한 작업
- webpack config 셋업
- 프론트 보일러플레이트 작성

**Comment by JeongHoJeong** [comment]
@limgit 이 이슈 작업 진행하고 계신건가요? 아니면 제가 작업하면 될까요?

**Comment by limgit** [comment]
@JeongHoJeong 진행하고 있지는 않습니당. 디렉토리 구조는 어떻게 하실 생각이신가요

**Comment by JeongHoJeong** [comment]
@limgit `app/client` 밑에 웹뷰 컴포넌트들을 넣을 생각입니다. 그 밑에는 presentational component들을 모으는 `component`와 container component들을 모으는 `container` 디렉토리를 각각 둘 생각입니다. 크게 특별할 건 없습니다.
